### PR TITLE
Sync master with current state of develop

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Comment by erickpeirson** [comment]
@bbarker Think we're ready for a new version?

**Comment by bbarker** [comment]
@erickpeirson sure, should I just bump [this](https://github.com/cul-it/arxiv-zero/blob/master/zero/config.py#L5) to 0.2?

**Comment by erickpeirson** [comment]
Why don't I do it on #5, as I'm just now fixing merge conflicts.

**Comment by bbarker** [comment]
It looks like some of the things int he **TODO** in the README can perhaps be checked off.

**Pull request merged**
