### PR TITLE
Experimenting with Travis reporting to Github

### PR DESCRIPTION
**Pull request by erickpeirson**
Don't merge me!

### CODE REVIEW

**Comment by erickpeirson** [comment]
@bbarker Ok, watch this PR as the build proceeds. I would recommend choosing tags for these reports that we can use across projects. And you might use a different namespace, since these are more about build/run than code quality. For example, instead of ``code-quality/dockerrunzero`` you could use ``docker/run``.

**Comment by erickpeirson** [comment]
Yum isn't always so yummy...

**Comment by bbarker** [comment]
Yeah I think I saw the same issue yesterday, ran it again, and it worked ... I'll try to start another build

**Comment by erickpeirson** [comment]
Looks good now. I'll let you merge this if you want

**Pull request merged**
