### PR TITLE
WIP: attempt to use pipenv

### PR DESCRIPTION
**Pull request by bbarker**
initial support for pipenv, pending:
 1. https://github.com/cul-it/arxiv-base/pull/12
 2. https://github.com/pypa/pipenv/issues/1231

Not sure of the best way to handle (2) - may be worth discussion. Also, currently pipenv only supports production and development groups for dependencies, but support for something more [is planned](https://github.com/pypa/pipfile/issues/99) - please add your support/comments there.

### CODE REVIEW

**Comment by erickpeirson** [comment]
Per our discussion Tuesday, we can go ahead and use pypi to distribute the arXiv Base UI package.

**Comment by bbarker** [comment]
As discussed on slack, I'll try to add in requirements generation as a git hook

**Comment by bbarker** [comment]
A note on git hooks (maybe others know this): you have to copy them into the .git/hooks directory on each local repo for them to work. I guess this could also be done in the CI stage, assuming our CI server is able to commit (if we want to be rigorous, but it probably isn't necessary for the requirements here)

**Comment by erickpeirson** [comment]
Let's not worry too much about that right now. While it's true that a requirements.txt file may be helpful for others, that's a pretty minimal concern currently. Let's press ahead.

**Comment by erickpeirson** [comment]
@bbarker I'm perfectly happy to ignore the pylint result and get this merged, if you're happy with that. Merge when ready!

**Comment by bbarker** [comment]
woo finally got pydocstyle to run

**Comment by erickpeirson** [comment]
Nice

**Pull request merged**
